version: "1"

volumes:
    budget-app-data:

services:
    mysql:
        image: "mysql:8.0.31"
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=budget
        volumes:
            - budget-app-data:/var/lib/mysql

    rabbit:
        image: "rabbitmq:3-management"
        hostname: "rabbit"
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=budg3t
            - RABBITMQ_DEFAULT_PASS=budg3t
            - RABBITMQ_DEFAULT_VHOST=budg3t